## For Japanese
# export GTK_IM_MODULE='ibus'
# export QT_IM_MODULE='ibus'
# ibus-daemon &
# export XMODIFIERS='@im=ibus'

# For sound
# /usr/bin/start-pulseaudio-x11

## For nvidia prime
# xrandr --setprovideroutputsource modesetting NVIDIA-0
# xrandr --setprovideroutputsource NVIDIA-0 Intel
xrandr --auto
#xrandr --dpi 96

#exec /usr/bin/xbindkeys & /usr/bin/dwmstatus & /usr/bin/dwm
#
#/usr/bin/xbinkeys
#xrdb -merge .Xresources
#xsetroot -cursor_name left_ptr 
#setxkbmap -layout fr 
#trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 6 --transparent true --alpha 0 --tint 0x000000 --height 16 &
#exec /usr/bin/xmonad



## For I3
# /usr/lib/policykit-1/polkitd --no-debug
# exec /usr/bin/xcompmgr -n & exec /usr/bin/xbindkeys
# xrandr --setprovideroutputsource NVIDIA-0 Intel
#xrandr --auto
exec /usr/bin/i3

