# Source Prezto.
if [[ -s ~/.zprezto/init.zsh ]]; then
  source ~/.zprezto/init.zsh
else
  echo "Error sourcing zpresto!"
fi

export PATH=$PATH:/usr/local/bin:$HOME/go/bin

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export VISUAL='vim'
  export EDITOR='vim'
else
  export EDITOR='nvim'
  export VISUAL='nvim'
  alias vim='nvim'
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source /opt/ros/noetic/setup.zsh
# source $HOME/devel/src/catkin_ws/devel/setup.zsh
#source $HOME/devel/src/catkin_ws/devel/setup.zsh
#source $HOME/devel/src/catkin_data_ws/devel/setup.zsh
#source $HOME/hrg/src/catkin_ws_choreonoid/devel/setup.zsh
#source $HOME/src/catkin_ws_moveit/devel/setup.zsh
#source $HOME/devel/src/catkin_ws_ana/devel/setup.zsh


# drcutils
source /home/arnaud/hrg/drcutil/setup.bash

# mc_rtc
export PATH=/home/arnaud/mc_rtc_install/bin:$PATH
export LD_LIBRARY_PATH=/home/arnaud/mc_rtc_install/lib:$LD_LIBRARY_PATH
export PKG_CONFIG_PATH=/home/arnaud/mc_rtc_install/lib/pkgconfig:$PKG_CONFIG_PATH
export PYTHONPATH=/home/arnaud/mc_rtc_install/lib/python3.8/site-packages:$PYTHONPATH
source /home/arnaud/mc_rtc/catkin_ws/devel/setup.zsh

source $HOME/src/ana/catkin_ws_ana/devel/setup.zsh
source $HOME/hrg/src/catkin_ws_choreonoid/devel/setup.zsh --extend


export LD_LIBRARY_PATH="/usr/local/lib:/usr/local/xsens/lib:$LD_LIBRARY_PATH"
export CMAKE_PREFIX_PATH="/usr/local/lib/cmake:/home/arnaud/.local/share/cmake:/home/arnaud/openrtp/share/choreonoid/cmake:${CMAKE_PREFIX_PATH}"
export PYTHONPATH="/usr/local/lib/python3/dist-packages:$PYTHONPATH"
export COPPELIASIM_ROOT_DIR="/opt/CoppeliaSim_Edu_V4_2_0_Ubuntu20_04"

# HRP4LIRMM
export ROS_IP="10.4.5.42"
export ROS_HOSTNAME="$ROS_IP"
export ROS_MASTER_URI="http://10.4.5.42:11311"

ros_local()
{
  export ROS_IP="127.0.0.1"
  export ROS_HOSTNAME="$ROS_IP"
  export ROS_MASTER_URI="http://127.0.0.1:11311"
}

# hrp4cr
ros_hrp4cr()
{
  export ROS_IP="150.18.66.123"
  export ROS_HOSTNAME="$ROS_IP"
  export ROS_MASTER_URI="http://150.18.66.103:11311"
}
ros_local

alias cmake_ninjacc="cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  -GNinja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache"
alias ccmake_ninjacc="ccmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  -GNinja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache"
alias cmake="cmake_ninjacc -DCMAKE_BUILD_TYPE=Release"
alias cmake_mc="cmake -DCMAKE_BUILD_TYPE=/home/arnaud/mc_rtc_install"
alias ccmake="ccmake_ninjacc"
alias cmakerd="cmake_ninjacc -DCMAKE_BUILD_TYPE=RelWithDebInfo"
alias cmaked="cmake_ninjacc -DCMAKE_BUILD_TYPE=Debug"
alias m='ninja'
alias n='ninja'
alias smi="sudo ninja install"
alias mi="ninja install"
alias sni="sudo ninja install"
alias ni="ninja install"
