# Source Prezto.
if [[ -s ~/.zprezto/init.zsh ]]; then
  source ~/.zprezto/init.zsh
else
  echo "Error sourcing zpresto!"
fi

export PATH=$PATH:/usr/local/bin

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export VISUAL='vim'
  export EDITOR='vim'
else
  export EDITOR='nvim'
  export VISUAL='nvim'
  alias vim='nvim'
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source /opt/ros/noetic/setup.zsh
source ~/src/catkin_ws/devel/setup.zsh
source ~/src/catkin_ws_ana/devel/setup.zsh
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"

# for pinocchio 
# https://stack-of-tasks.github.io/pinocchio/download.html
export PATH=/opt/openrobots/bin:$PATH
export PKG_CONFIG_PATH=/opt/openrobots/lib/pkgconfig:$PKG_CONFIG_PATH
export LD_LIBRARY_PATH=/opt/openrobots/lib:$LD_LIBRARY_PATH
export PYTHONPATH=/opt/openrobots/lib/python2.7/site-packages:$PYTHONPATH
export CMAKE_PREFIX_PATH="/home/arnaud/openrtp/share/choreonoid/cmake:${CMAKE_PREFIX_PATH}"

alias cmake_ninjacc="cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  -GNinja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache"
alias ccmake_ninjacc="ccmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  -GNinja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache"
alias cmake="cmake_ninjacc -DCMAKE_BUILD_TYPE=Release"
alias ccmake="ccmake_ninjacc"
alias cmakerd="cmake_ninjacc -DCMAKE_BUILD_TYPE=RelWithDebInfo"
alias cmaked="cmake_ninjacc -DCMAKE_BUILD_TYPE=Debug"
alias m='ninja'
alias n='ninja'
alias smi="sudo ninja install"
alias mi="ninja install"
alias sni="sudo ninja install"
alias ni="ninja install"
