#
# ~/.bashrc
#

source /etc/profile
source /etc/bash.bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# enable color support of ls and also add handy aliases
if [ "$TERM" != "dumb" ]; then
  eval "`dircolors ~/.mydircolors`"
  alias ls='ls --color=auto'
fi

export EDITOR='nvim'
export LANG=en_US.utf8
set shell=/bin/bash

export SRC_DIR="/home/arnaud/src/choreonoid"

shopt -s histappend
PROMPT_COMMAND='history -a'

source ~/.term_common

export PATH="$PATH:/home/arnaud/programmation/scripts:/usr/lib/qt/bin:/usr/local/bin/zotero:/usr/local/MATLAB/R2012a/bin:/home/arnaud/.i3:/usr/local/cuda-6.5/bin"
export TERMINAL=/usr/bin/urxvt
export LD_LIBRARY_PATH="/usr/lib:/usr/local/lib:/opt/intel/mkl/lib/intel64:/usr/lib/x86_64-linux-gnu:/home/arnaud/PhD/Code/lsd_slam/lsd_slam_core/lib:/usr/local/lib/roboptim-core:/usr/local/lib64"

alias android-connect="sudo mtpfs -o allow_other /mnt/ANDROID"
alias android-disconnect="fusermount -u /mnt/ANDROID"
alias http="python -m http.server"
alias yaourtf="yaourt --noconfirm"

## Automatic cd
shopt -s autocd

## Improve bash completion
bind "TAB:menu-complete"
bind "set show-all-if-ambiguous on"

command fortune -a | fmt -80 -s | $(shuf -n 1 -e cowsay cowthink) -$(shuf -n 1 -e b d g p s t w y) -f $(shuf -n 1 -e $(cowsay -l | tail -n +2)) -n

## Load autojump
source /usr/share/autojump/autojump.sh

# ROS
source /opt/ros/indigo/setup.bash
source ~/catkin_ws/devel/setup.bash
alias cws="source ~/src/catkin_ws/devel/setup.bash"
# export ROS_PACKAGE_PATH="$ROS_PACKAGE_PATH:/home/arnaud"


## Powerline status bar
function _update_ps1() {
  export PS1="$(~/.powerline-shell.py $? 2> /dev/null)"
}
export PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
